### ISSUE TITLE
Uploading from iphone

### ISSUE THREAD

**Issue by pedbre08** [rootcanal/whereikeepinfo#7]
When uploading from my iPhone (iOS 8.3) on safari I was only offered the option of uploading an image (take photo or choose from library) when I choose a photo to upload the upload failed.

**Comment by rootcanal** [comment]
do you know the file size for the image you tried to upload? Looks like I had the default to be rather low in nginx. I've upped it and restarted. It may still not work for files >10MB currently. If yours is smaller, could you try uploading again and report back?

**Comment by pedbre08** [comment]
It worked. Now I'm looking at it and can't find the place where I can share the file, send it to someone. For example, there's no evidence of that list of users that I complained about as being to cramped.

b

**Comment by rootcanal** [comment]
I've changed things around a good deal to try and make it work on mobile. I don't have an iphone to test with but it's working on my android chrome app. Let me know if there are still any issues or if that solves it.

**Comment by rootcanal** [comment]
Oh I also changed around the share-with display settings to make it less cramped :)

**Comment by pedbre08** [comment]
Btw the photos I uploaded (which worked) were taken on my iPhone. I had no luck determining their size.

Above you'll see how it appears on my phone when I load the site. It's a little wonky as trying to scroll through the text the black section doesn't move much and the text will slip underneath it. However, if you zoom out this issue is avoided as no horizontal scrolling is necessary.

I will note however that when I loaded the login screen I could not log out and had to click into the fields pushed to the edge of my screen. 

Similarly on the account settings page I could not zoom out:





An example of text slipping under the black. 

Also I'm still unclear how I can share files. I can see the list of files I've uploaded and those that have been shared with me but further activity that I can do is unclear. 

b

**Comment by rootcanal** [comment]
hmm. sounds like i need to grab an iphone to test with...

**Comment by rootcanal** [comment]
Here's how the 'uploaded files' tab looks on my android. When I click the 'change share settings' button for files i've uploaded I am able to select folks one at a time to share it with.

![screenshot_2015-07-23-16-20-24](https://cloud.githubusercontent.com/assets/1310668/8864454/f6c8919a-3156-11e5-9c37-e55d7ab334b5.png)

**Comment by pedbre08** [comment]
Okay. 
That worked. I may request that since sharing is the primary function of his service so far as I understand it, that this button be renamed and prioritized. 

Btw selecting who I want to share with on iPhone is easy. Practically pleasurable. 

I volunteer my phone for testing when we are in sustained proximity. 

b

**Comment by pedbre08** [comment]
Also, and this is dumb because what's cool about whereinfokeepsdot is not the other stuff but either we need to be able to name stuff and like sort it in lists and folders or something.
Also are thumbnails crazy?

b
